from collections import deque
d=deque()
d.append(1)
d.append(2)
d.append(3)
d.appendleft(4)
print(d)
d.pop()
print(d)
d.popleft()
print(d)
d.extend([7,8,9])
print(d)
d.extendleft([11,12,13])
print(d)
d.rotate(1) #(n)=> rotate all elements to n times to right
print(d)
d.rotate(-2)
print(d)
d.clear()
print(d)